development:
  bucket: decorator_dev
  access_key_id: AKIAI5K5E3AZ5BCSH4BQ
  secret_access_key: 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
production:
  bucket: decorator
  access_key_id: AKIAI5K5E3AZ5BCSH4BQ
  secret_access_key: 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